/*
 * SPDX-License-Identifier: GPL-3.0-or-later WITH additional permission
 * Copyright (c) 2026 SkyBlock Simplified GbR
 *
 * This file is part of SkyBlock Simplified. See the LICENSE file in the
 * project root for license terms and the Minecraft linking exception.
 */

package sbs.modid.client.skills.hunting.model;

import sbs.modid.client.core.data.VersionedDocument;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The shard catalogue file: which shards exist, which of them cannot be consumed, and how many
 * shards each tier of an attribute takes.
 *
 * <p><b>This replaces a catalogue that was learned at runtime, and the swap is the point.</b> The
 * previous {@code ShardCatalog} assembled its list from the live Bazaar product map plus whatever
 * menus the player had happened to open. That made "missing" a function of what the GUI had shown,
 * which is circular: a shard the menu never displayed could never be reported missing, and a failed
 * or slow Bazaar pull silently shrank the whole list. The set of shards that exist is static data
 * and belongs in a versioned file like every other curated dataset in this tree.
 *
 * <p><b>Regenerated by {@code scripts/shards_import.py}</b> from Hypixel's keyless Bazaar snapshot,
 * which is the only public source that lists all 320 of them - the keyless items resource carries
 * none (re-checked 2026-08-20, unchanged since 2026-08-10). Bump {@code dataVersion} in the same
 * commit as a regeneration.
 *
 * <p><b>What the generator can fill, and what it cannot.</b> The Bazaar states an id and nothing
 * else, so {@code name}, {@code displayName} and {@code canonicalId} are complete for all 320 and
 * every other field ships empty. That is deliberate rather than unfinished: {@code rarity},
 * {@code ability}, {@code family}, {@code alignment} and {@code shardId} are in no keyless source,
 * and writing them from memory or from another mod's data file is exactly the invented-dataset
 * failure {@code Certainty} exists to prevent. The fields are in the schema so filling them later
 * is a data edit rather than a code change, and every consumer already reads the empty case:
 * rarity is read off the item at runtime, and the rest are carried for display only.
 *
 * <p><b>Partial coverage is normal here, with one exception.</b> A document with no shards at all
 * is refused - a catalogue that lists nothing reports every shard as neither missing nor owned, and
 * the previously loaded copy keeps serving instead.
 */
public final class ShardData implements VersionedDocument {

    public int schemaVersion = 1;
    public int dataVersion;
    public String generatedAt = "";

    /** Where the generator took the list from, for the settings status line. */
    public String source = "";

    /**
     * Shards per attribute tier, by {@link ShardRarity#name()}, index 0 being tier 1.
     *
     * <p>What {@code ShardLevelling} turns a "Syphon N shards to level up!" line plus a roman tier
     * into an exact owned amount with. <b>Ships empty</b>, for the reason above: the per-tier split
     * is in no keyless source, and a wrong split produces a confident wrong number rather than a
     * visibly absent one. With no table for a rarity the amount is reported unknown and the Hunting
     * Box's own {@code "Owned: N Shards"} line - which is exact and needs no table - answers
     * instead. Filling one rarity's row here is all it takes to switch the menu path on.
     */
    public Map<String, List<Integer>> levelling = new LinkedHashMap<>();

    /**
     * Shard names that cannot be consumed, and are therefore excluded from the total.
     *
     * <p>These count towards nothing: they are not missing when absent and not owned when held, so
     * a player is never sent shopping for one. Ships empty, and while it is empty the total is the
     * full catalogue - too high by however many of these there turn out to be, which the panel says
     * rather than hides.
     */
    public List<String> unconsumable = new ArrayList<>();

    public List<ShardDefinition> shards = new ArrayList<>();

    public ShardData() {
    }

    @Override
    public int schemaVersion() {
        return schemaVersion;
    }

    @Override
    public int dataVersion() {
        return dataVersion;
    }

    @Override
    public boolean valid() {
        return shards != null && !shards.isEmpty();
    }

    /** Drops unusable entries and replaces any null collection. Called once when a copy goes live. */
    public void link() {
        if (shards == null) {
            shards = new ArrayList<>();
        } else {
            shards.removeIf(shard -> shard == null || !shard.valid());
        }
        if (levelling == null) {
            levelling = new LinkedHashMap<>();
        }
        if (unconsumable == null) {
            unconsumable = new ArrayList<>();
        }
    }
}
