/*
 * SPDX-License-Identifier: GPL-3.0-or-later WITH additional permission
 * Copyright (c) 2026 SkyBlock Simplified GbR
 *
 * This file is part of SkyBlock Simplified. See the LICENSE file in the
 * project root for license terms and the Minecraft linking exception.
 */

package sbs.modid.client.economy.minions.model;

import sbs.modid.client.core.data.VersionedDocument;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The minion catalog data file ({@code minions.json}): every minion type with its per-tier stats,
 * per-harvest outputs, Super-Compactor product chains and the skill-XP-per-item table. Generated by
 * {@code scripts/minion_catalog_import.py} - see its header for sources and certainty tags.
 *
 * <p><b>Costs are marginal.</b> A tier's {@code cost} is the materials for upgrading from the tier
 * below (the previous-tier minion itself is implied, never listed). A from-scratch craft cost is
 * the sum over tiers 1..N, and is undefined when any tier below is not craftable
 * ({@code source} = "drop", e.g. the Snow Minion's tier I, which only comes from Gifts).
 *
 * <p><b>Production cadence.</b> {@code actionsPerHarvest} is 2 for nearly every minion (one action
 * places, the next collects) and 1 for the three exceptions (Fishing, Melon, Pumpkin). Any rate
 * computed from {@code actionSeconds} without this factor is 2x optimistic.
 */
public final class MinionData implements VersionedDocument {

    public int schemaVersion = 1;
    public int dataVersion;
    public String generatedAt = "";

    public List<Minion> minions = new ArrayList<>();

    /** item id -> next compacted form (generic chains; per-minion sc3000 wins where present). */
    public Map<String, Chain> compactChains = new HashMap<>();

    /** Skill XP per item on collection. Certainty-tagged; "unknown" items are absent, not zero. */
    public List<XpRow> xp = new ArrayList<>();

    /** One minion type across all its tiers. */
    public static final class Minion implements MinionModifierData.MinionDataType {
        public String type = "";
        public String name = "";
        /** FARMING / MINING / COMBAT / FORAGING / FISHING / SLAYER. */
        public String skill = "";

        @Override
        public String type() {
            return type;
        }

        @Override
        public String skill() {
            return skill;
        }
        public int maxTier;
        /** 2 for almost everything; 1 for Fishing / Melon / Pumpkin. */
        public int actionsPerHarvest = 2;

        /**
         * Additive speed % each placed minion OF THIS TYPE gives every one of them - the Inferno
         * Minion's "Rising Celsius" and, so far, nothing else. Capped at {@link #maxPct}.
         */
        public double perMinionPct;
        public double maxPct;

        /** The self-boost for {@code placed} copies of this type, already capped. */
        public double selfBoostPct(int placed) {
            if (perMinionPct <= 0 || placed <= 0) {
                return 0;
            }
            double total = perMinionPct * placed;
            return maxPct > 0 ? Math.min(maxPct, total) : total;
        }
        public String unlockCollection;
        public String unlockCollectionTier;
        public List<Output> outputs = new ArrayList<>();
        /** What a Super Compactor turns the drops into, as from->item steps. */
        public List<Sc3000> sc3000;
        public List<Tier> tiers = new ArrayList<>();

        /** The tier entry, or {@code null} when out of range. */
        public Tier tier(int number) {
            for (Tier tier : tiers) {
                if (tier.tier == number) {
                    return tier;
                }
            }
            return null;
        }
    }

    /** One drop stream: average items per harvest (fractions encode chance-based drops). */
    public static final class Output {
        public String item = "";
        public String name = "";
        public double amount = 1;
        public String certainty = "";
    }

    /** One Super-Compactor step: {@code ratio} x {@code from} becomes 1 x {@code item}. */
    public static final class Sc3000 {
        public String item = "";
        public String from = "";
        public int ratio = 160;
    }

    /** One tier's stats and its marginal upgrade cost. */
    public static final class Tier {
        public int tier;
        public String itemId = "";
        public String rarity = "";
        /** Base time between actions in seconds; a harvest takes {@code actionsPerHarvest} of them. */
        public double actionSeconds;
        /** NEU's disagreeing figure where the sources split (wiki value kept above). */
        public Double actionSecondsNeu;
        public String statsCertainty = "";
        /** Capacity in ITEMS (not slots). */
        public int storage;
        /** recipe | npc | drop - how this tier is reached from the one below. */
        public String source = "";
        /** Marginal materials; "COINS" is the pseudo-id for raw coin costs. */
        public List<CostRef> cost;
        public String costCertainty;
        /** The trade NPC when {@code source} is "npc" (Bulvar, Tony, ...). */
        public String npc;
    }

    /** One cost line. */
    public static final class CostRef {
        public String id = "";
        public String name = "";
        public double count;
    }

    /** One generic compact step (Super-Compactor semantics: enchanted form wins). */
    public static final class Chain {
        public String to = "";
        public int ratio;
        public String certainty = "";
    }

    /** One skill-XP-per-item fact. */
    public static final class XpRow {
        public String item = "";
        public String skill = "";
        public double xp;
        public String certainty = "";
    }

    public MinionData() {
    }

    @Override
    public int schemaVersion() {
        return schemaVersion;
    }

    @Override
    public int dataVersion() {
        return dataVersion;
    }

    @Override
    public boolean valid() {
        return minions != null && !minions.isEmpty();
    }

    /**
     * Finishes parsing: drops unusable entries so no consumer meets a half-null minion. Partial
     * coverage stays normal - a file with 40 of 61 types is a data problem to report, not a crash.
     */
    public void link() {
        if (minions == null) {
            minions = new ArrayList<>();
        }
        minions.removeIf(minion -> minion == null || minion.type == null || minion.type.isBlank()
                || minion.tiers == null || minion.tiers.isEmpty());
        for (Minion minion : minions) {
            if (minion.outputs == null) {
                minion.outputs = new ArrayList<>();
            }
            minion.outputs.removeIf(output -> output == null || output.item == null
                    || output.item.isBlank() || output.amount <= 0);
            minion.tiers.removeIf(tier -> tier == null || tier.tier <= 0);
        }
        if (compactChains == null) {
            compactChains = new HashMap<>();
        }
        if (xp == null) {
            xp = new ArrayList<>();
        }
        xp.removeIf(row -> row == null || row.item == null || row.item.isBlank() || row.xp < 0);
    }
}
