/*
 * SPDX-License-Identifier: GPL-3.0-or-later WITH additional permission
 * Copyright (c) 2026 SkyBlock Simplified GbR
 *
 * This file is part of SkyBlock Simplified. See the LICENSE file in the
 * project root for license terms and the Minecraft linking exception.
 */

package sbs.modid.client.economy.minions.model;

import sbs.modid.client.core.data.VersionedDocument;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The minion modifier data file ({@code minion-modifiers.json}): fuels, hoppers, upgrade-slot
 * items, storage chests, crystals, beacon, island-wide boosts, mayor perks and the slot-unlock
 * thresholds. Generated by {@code scripts/minion_catalog_import.py} from the wiki's verified
 * tables (2026-08-07).
 *
 * <p>The two figures that must never be conflated: {@code speedPct} entries are <b>additive</b>
 * percentages applied as {@code time = base / (1 + total/100)}, while {@code outputMult} entries
 * multiply the <i>drops</i> and leave the action time alone (Tasty Cheese, the Catalysts, Derpy).
 */
public final class MinionModifierData implements VersionedDocument {

    public int schemaVersion = 1;
    public int dataVersion;

    public List<Fuel> fuels = new ArrayList<>();
    public List<Hopper> hoppers = new ArrayList<>();
    public List<Upgrade> upgrades = new ArrayList<>();
    /** Auto Smelter / Dwarven replacement: raw drop id -> smelted id. */
    public Map<String, String> smeltMap = new HashMap<>();
    /** Compactor (block forms): drop id -> block step. The enchanted chains live in the catalog. */
    public Map<String, Compact> blockMap = new HashMap<>();
    public List<Storage> storages = new ArrayList<>();
    public List<Crystal> crystals = new ArrayList<>();
    public Beacon beacon = new Beacon();
    public List<IslandWide> islandWide = new ArrayList<>();
    public List<PermanentPerMinion> permanentPerMinion = new ArrayList<>();
    public List<Mayor> mayors = new ArrayList<>();
    public List<Pet> pets = new ArrayList<>();

    /** Unique-craft counts at which the next placement slot unlocks (base 5 before the first). */
    public List<Integer> slotThresholds = new ArrayList<>();
    public int baseSlots = 5;
    public int communityShopSlots = 5;
    /** SkyBlock XP for crafting a unique minion tier; index = tier (index 0 unused). */
    public List<Integer> skyblockXpPerTier = new ArrayList<>();

    public static final class Fuel {
        public String id = "";
        public String name = "";
        /** Additive speed percentage (0 for the output-multiplier fuels). */
        public double speedPct;
        /** Drop multiplier (1.0 for the speed fuels). */
        public double outputMult = 1.0;
        /**
         * MULTIPLICATIVE speed factor, Inferno fuels only: the game divides the action time by
         * {@code (1 + speedBuffs) * (1 + speedMult)}, so a "20x" fuel is effectively 21x. Never
         * add this to {@link #speedPct} - the two combine differently.
         */
        public double speedMult;
        /** 0 = permanent. Consumed fuels stack to 64, so duration extends by stacking. */
        public double durationHours;
        public boolean permanent;
        /** The only minion type that accepts this fuel, or {@code null} for any. */
        public String restrictType;
        /** Replaces the normal drop on {@link #specialtyChance} of harvests (Inferno fuels). */
        public String specialtyItem;
        public double specialtyAmount;
        public double specialtyChance;
        /**
         * Replaces the minion's drops ENTIRELY with this item (Thorny Vines makes a Flower Minion
         * produce only Wild Roses; the Day/Nightswitch pin a Sunflower Minion to one bloom).
         */
        public String replaceItem;
        public double replaceAmount;
        /** Rolled once per harvest each (Legendary Inferno fuel's Chili Pepper and friends). */
        public List<RareDrop> rareDrops;
        public String note;

        /** Whether this fuel does anything in {@code minion}'s fuel slot. */
        public boolean appliesTo(MinionDataType minion) {
            return restrictType == null || restrictType.equalsIgnoreCase(minion.type());
        }
    }

    /** One per-harvest chance drop. */
    public static final class RareDrop {
        public String item = "";
        public double chance;
    }

    public static final class Hopper {
        public String id = "";
        public String name = "";
        /** Fraction of the NPC sell price the hopper pays (0.50 / 0.70). */
        public double cut;
    }

    /** One upgrade-slot item; see the generator script for the {@code kind} vocabulary. */
    public static final class Upgrade {
        public String id = "";
        public String name = "";
        public String kind = "";
        public double speedPct;
        public double outputMult = 1.0;
        public double chance;
        public String item;
        public Integer islandLimit;
        public Integer cooldownSeconds;
        public String from;
        public String to;
        /** Auto Smelter (and the Dwarven compactor) run drops through {@link #smeltMap} first. */
        public boolean smelts;
        /** Extra drops this upgrade adds per harvest (Corrupt Soil, Enchanted Egg / Shears). */
        public List<Add> adds;
        public String restrictSkill;
        public String restrictType;
        /** Several allowed types (Corrupt Soil's mob-spawning list); null = no list restriction. */
        public List<String> restrictTypes;
        public String note;

        /** Whether this upgrade does anything at all on {@code minion}. */
        public boolean appliesTo(MinionDataType minion) {
            if (restrictType != null && !restrictType.equalsIgnoreCase(minion.type())) {
                return false;
            }
            if (restrictTypes != null && !restrictTypes.isEmpty()
                    && restrictTypes.stream().noneMatch(t -> t.equalsIgnoreCase(minion.type()))) {
                return false;
            }
            return restrictSkill == null || restrictSkill.equalsIgnoreCase(minion.skill());
        }
    }

    /**
     * The two fields an applicability check needs, so this model does not have to depend on the
     * minion catalog just to answer "does this upgrade work here".
     */
    public interface MinionDataType {
        String type();

        String skill();
    }

    /** One extra drop an upgrade adds per harvest. */
    public static final class Add {
        public String item = "";
        public double amount = 1;
    }

    /** One compacting step: {@code ratio} of the source becomes one {@link #to}. */
    public static final class Compact {
        public String to = "";
        public int ratio = 1;
    }

    public static final class Storage {
        public String id = "";
        public String name = "";
        /** Added capacity in slot-equivalents (x64 items). */
        public int slots;
    }

    public static final class Crystal {
        public String id = "";
        public String name = "";
        /** The boosted minion family, or {@code null} when the note narrows it instead. */
        public String skill;
        public double speedPct;
        /** Extra additive % per unique placed minion of {@link #skill} (Cornucopia only). */
        public double perUniqueSkillPct;
        public String note;
    }

    public static final class Beacon {
        public double perTierPct = 2;
        public int maxTier = 5;
        public double scorchedBonusPct = 1;
        /** A beacon is only live while fueled: one Power Crystal per this many hours. */
        public double powerHours = 48;
        public String powerItem = "POWER_CRYSTAL";
        public String scorchedPowerItem = "SCORCHED_POWER_CRYSTAL";
    }

    public static final class IslandWide {
        public String id = "";
        public String name = "";
        public double speedPct;
        public String note;
    }

    public static final class PermanentPerMinion {
        public String id = "";
        public String name = "";
        public double speedPct;
        /** Free Will only: stay chance = base + perTier x tier; failure deletes the minion. */
        public Double stayChanceBase;
        public Double stayChancePerTier;
        public String note;
    }

    public static final class Mayor {
        public String name = "";
        public String perk = "";
        public String skill;
        public double speedPct;
        public double outputMult = 1.0;
    }

    public static final class Pet {
        public String id = "";
        public String name = "";
        /** At pet level 100; scales linearly with level. */
        public double maxSpeedPct;
        public String note;
    }

    public MinionModifierData() {
    }

    @Override
    public int schemaVersion() {
        return schemaVersion;
    }

    @Override
    public int dataVersion() {
        return dataVersion;
    }

    @Override
    public boolean valid() {
        return fuels != null && !fuels.isEmpty() && hoppers != null && !hoppers.isEmpty();
    }

    /** The hopper entry by id, or {@code null}. */
    public Hopper hopper(String id) {
        for (Hopper hopper : hoppers) {
            if (hopper.id.equals(id)) {
                return hopper;
            }
        }
        return null;
    }

    /** The fuel entry by id, or {@code null}. */
    public Fuel fuel(String id) {
        for (Fuel fuel : fuels) {
            if (fuel.id.equals(id)) {
                return fuel;
            }
        }
        return null;
    }

    /** The upgrade entry by id, or {@code null}. */
    public Upgrade upgrade(String id) {
        for (Upgrade upgrade : upgrades) {
            if (upgrade.id.equals(id)) {
                return upgrade;
            }
        }
        return null;
    }

    /**
     * Placement slots for a unique-craft count: base + one per crossed threshold + the community
     * slots the caller says are bought (0-{@link #communityShopSlots}).
     */
    public int slotsFor(int uniqueCrafts, int communityBought) {
        int slots = baseSlots;
        for (int threshold : slotThresholds) {
            if (uniqueCrafts >= threshold) {
                slots++;
            }
        }
        return slots + Math.max(0, Math.min(communityBought, communityShopSlots));
    }
}
