/*
 * SPDX-License-Identifier: GPL-3.0-or-later WITH additional permission
 * Copyright (c) 2026 SkyBlock Simplified GbR
 *
 * This file is part of SkyBlock Simplified. See the LICENSE file in the
 * project root for license terms and the Minecraft linking exception.
 */

package sbs.modid.client.helper.inventory.model;

import sbs.modid.client.core.data.VersionedDocument;

import java.util.ArrayList;
import java.util.List;

/**
 * The accessory catalogue file: every accessory Hypixel publishes, with its upgrade ladder.
 *
 * <p>Regenerated by {@code scripts/accessories_import.py} from
 * {@code api.hypixel.net/v2/resources/skyblock/items}, which needs no API key - so the bundled copy
 * is as authoritative as anything the backend could serve, and a client that never reaches the
 * network still knows the whole game's accessory list.
 *
 * <p>Unlike the Fairy Souls file, partial coverage here is <b>not</b> a normal state: a catalogue
 * missing entries reports accessories as owned-complete that are not, so a document with no
 * accessories at all is refused and the previously loaded copy keeps serving.
 */
public final class AccessoryData implements VersionedDocument {

    public int schemaVersion = 1;
    public int dataVersion;
    public String generatedAt = "";

    /** Hypixel's own {@code lastUpdated} on the resource this was generated from, for the status line. */
    public long sourceUpdated;

    public List<Accessory> accessories = new ArrayList<>();

    public AccessoryData() {
    }

    @Override
    public int schemaVersion() {
        return schemaVersion;
    }

    @Override
    public int dataVersion() {
        return dataVersion;
    }

    @Override
    public boolean valid() {
        return accessories != null && !accessories.isEmpty();
    }

    /** Drops unusable entries. Called once when a document becomes live. */
    public void link() {
        if (accessories == null) {
            accessories = new ArrayList<>();
            return;
        }
        accessories.removeIf(accessory -> accessory == null || !accessory.valid());
    }
}
